### PR TITLE
fix: make git run_command synchronous

### PR DESCRIPTION
**Pull request by mkenigs**
We don't need run_command to be async, so it's just causing pain.

### CODE REVIEW

**Comment by zmitchell** [comment]
My hero

**Comment by mkenigs** [comment]
The `async` stuff hasn't been bothering me, but as I'm writing new `Floxmeta` code I'd rather keep that synchronous if that's our ultimate goal

**Comment by mkenigs** [comment]
I will probably want to make some more methods synchronous, which I can either do here or in separate commits/PRs

**Review by zmitchell — APPROVED** [review]

**Comment by zmitchell** [comment]
We can migrate away from `async` in pieces, let's just do each piece when it's most convenient.

**Comment by mkenigs** [comment]
No user facing changes

**Pull request merged**
