### PR TITLE
chore: tweak manifest build verbosity

### PR DESCRIPTION
**Pull request by limeytexan**
## Proposed Changes

Following the addition of the makefile verbosity macros, use them to improve the signal-to-noise ratio of the text coming out of manifest builds. This is just an initial stab to get the ball rolling; I don't doubt there will be further modifications to follow.

## Release Notes

N/A

### CODE REVIEW

**Review by mkenigs — CHANGES_REQUESTED** [review]
Made some suggestions via https://github.com/flox/flox/pull/2416

**Comment by mkenigs** [comment]
@limeytexan looks like this broke a test

**Comment by limeytexan** [comment]
> @limeytexan looks like this broke a test

@ysndr identified that there were two test functions that were expecting to see a line that now appears only with verbosity 1 or above, so he added a patch to invoke those two tests with `_FLOX_PKGDB_VERBOSITY=1`

**Comment by mkenigs** [comment]
Flakey test, recorded and re-triggered

**Review by mkenigs — APPROVED** [review]

**Pull request merged**
