### PR TITLE
feat: automatically build environment after `flox pull`

### LINKED ISSUE #540: flox pull
# Acceptance Criteria

_pull existing anonymously_
**Given** I have `flox push` an environment called `ghudgins/material-ui` that contains a single package, `yarn`
**And** I am not authenticated with flox
**When** I `flox pull ghudgins/material-ui`
**Then** I see output:

```
⬇️ remote: pulling and preparing ghudgins/material-ui from https://{dev / staging / production}hub.flox.dev
```
**And When** the environment is pulled and built
**Then** I see additional output:

```
✨ pulled ghudgins/material-ui from https://{dev / staging / production}hub.flox.dev

You can activate this environment with `flox activate`
```
**And** I see a .flox is in my current directory 

Depends on flox push - https://github.com/flox/product/issues/589

### PR DESCRIPTION
**Pull request by ysndr**
close #540

### CODE REVIEW

**Comment by ghudgins** [comment]
when you update this can you tweak the message in pull 
`"⬇️ remote: pulling {owner/env} from {floxhuburl} to current directory"

there's a missing space and I wrote the sentence clumsily in the version in the app today.

**Comment by ysndr** [comment]
https://github.com/flox/flox/actions/runs/7227249590/job/19694509087?pr=655#step:8:307

ah jokes on me splitting this off of #654

**Comment by ghudgins** [comment]
okay, lets update it to `building` for now. although that term is going to come with its own problems here soon....I don't have a better suggestion and do agree with consistency

**Review by mkenigs — APPROVED** [review]
I think we're starting to use sentence case and maybe periods at the end of messages. Up to you if you want to change

**Comment by ysndr** [comment]
[3b62d7a](https://github.com/flox/flox/pull/655/commits/3b62d7a1760e1946b0471ea8e52a1ea9e5de6fd4) now uses spinners in consistency with the other commands.
If you prefer just a message, feel free to revert that commit

**Review by mkenigs — APPROVED** [review]

**Pull request merged**
