### PR TITLE
ci: Addressing comments from #320

### PR DESCRIPTION
**Pull request by garbas**
* duplicate of '.#flox' installable
* removing depth:0 from Checkout step to speed up

### CODE REVIEW

**Comment by ysndr** [comment]
The ci shell has not enough build inputs to build Flix (it was previously used to bump versions and update cargo lock). We should either add `inputsFrom = [ flox ]` or remove it and keep using the flox shell for now which comes with a few unnecessary dependencies (e.g. rust analyzer, rustfmt, ...)

**Comment by garbas** [comment]
I will remove the `.#ci` shell since it is not really used other than in release workflow. With a better caching and removing many pieces of the `flox/flox` the dependencies are going to be relatively small.

**Comment by garbas** [comment]
@ysndr but I will do this (1) in a separate PR and (2) do it after the release, since I don't want to poke with release workflow hours before the release. Sounds like a plan?

**Comment by ysndr** [comment]
Completely fine with me.
Using the flox shell works well enough a ci shell would just strip a few seconds off no need to over optimize that now

**Review by ysndr — APPROVED** [review]

**Pull request merged**
