### PR TITLE
feat: add global system option and config

### PR DESCRIPTION
**Pull request by ysndr**
Allows to build, install, publish, etc for non-native system types (given builder, cache support)

### CODE REVIEW

**Review by tomberek — COMMENTED** [review]
Unsure how this will interact with remote builds, cross-compile, non-local builds, etc.

**Comment by mkenigs** [comment]
@ysndr did you and @tomberek come to a conclusion about whether this should set host or target system?

**Comment by ysndr** [comment]
I think the conclusion was not to include that for the sake of being explicit in attr paths. Want to build/publish/etc for a different platform, use `<system>.<package name>`...

**Comment by ysndr** [comment]
yeah that's the concerns, it is a simple flag to change the default target (i don't think it should affect the host system, actually) similar to how there is a similarly simple flag for stabilities...
might want to say that alternative target systems should be expressed by way of the attrPath, I guess it all depends how much we want to lean into the nix layout.
This change is not blocking, we can make publish work with any target systems without it.

**Comment by mkenigs** [comment]
I think making it change the target is reasonable, especially for commands where the attrPath is hidden (e.g. pretty much all basic commands). If it does control target though, I'm not sure I'd put it in the config file, because that does seem more like something that configures the host system.

**Comment by tomberek** [comment]
I am okay with adding the option (it's basically the same option as Nix has).

I am not okay with this being used or recommended to do non-native system operations like build/publish/etc. It is too fragile and "high-expertise hack" for that.

**Comment by ysndr** [comment]
I mean it is explicitly unlike `NIX_SYSTEM`, as it would only affect the target system resolution (we're not setting `NIX_SYSTEM`). Wouldn't it thus be a less "expert'ish" compared to attribute paths?

**Comment by tomberek** [comment]
So this would be "set system for the purposes of manipulating the defaultAttrPathPrefix"? But it would not impact builtins.currentSystem? I can see that being useful. Not sure yet how this will interact with what naming schemes we document and describe to users.

**Comment by tomberek** [comment]
for many commands this is already supported by the existing resolver in flox:
```
flox build tracelinks
flox build aarch64-linux.tracelinks
flox build .#aarch64-linux.tracelinks
flox build floxpkgs#aarch64-linux.tracelinks
```

for publish; flox-bash had this option because it did not have a resolver. Once publish is brought into rust I'm not sure what this adds. We would have the same resolution take place as above.

for search (@aakropotkin): this would allow one to set a target system to search within other than the default. Similar to the proposed "-c" and "--all" which manipulate what is searched.

**Comment by stahnma** [comment]
Needs decision from @ysndr and @tomberek

**Comment by stahnma** [comment]
Needs decision from @ysndr and @tomberek

**Comment by tomberek** [comment]
@ysndr https://github.com/NixOS/nix/commit/bcbdb09ccf7ca007d3c2046177356fbfe7b72304

**Comment by ysndr** [comment]
Interesting, thanks for the pointer

Well, it was also to set the system for other things like `pull`, `activate` ..., but I dont see that on the GA roadmap yet anyway

**Pull request closed without merging**
