### PR TITLE
feat: handle expired tokens

### PR DESCRIPTION
**Pull request by ysndr**
* Validate `floxhub_token` on startup

* Warn if token is expired, or otherwise invalid

* Try unset token from user conf file, if validation failed.

May fail if the token is set by a global conf file or env var. Failures to unset from the user conf are _ignored_, but trying to use the token later will trigger a login flow regardless.

* Ensure present token for all modifying remote commands

### CODE REVIEW

**Comment by ysndr** [comment]
> May fail if the token is set by a global conf file or env var. Failures to unset from the user conf are ignored, but trying to use the token later will trigger a login flow regardless.

Not sure, how loudly this situation should be communicated to the user.
Right now its silently ignored and logged to `debug`.
I do think raising this as an error is _also_ reasonable, since the user will have the token set manually, and should similarly update it manually as well.
Setting the token through an env var is also very likely to coincide with non-interactive use cases of flox, where we can't prompt for a new token anyway.

cc @ghudgins @jennymahmoudi

**Comment by zmitchell** [comment]
My only concern with how this is implemented is that you'll see the token expiry errors when you run commands that don't need a token e.g. `install`.

**Comment by ysndr** [comment]
i implemented this after bringing it up in #1031, seems like "eager validation seems slightly better if all things are the same".

**Comment by zmitchell** [comment]
Alright, I disagree but I'm not going to block on it.

**Review by zmitchell — APPROVED** [review]

**Comment by zmitchell** [comment]
Failing functional tests

**Comment by mkenigs** [comment]
Oh whoops there was a flake, but there's also actual failures

**Comment by ysndr** [comment]
@mkenigs added a comment

**Review by mkenigs — APPROVED** [review]

**Pull request merged**
