### PR TITLE
fix: do not pull in user channels

### PR DESCRIPTION
**Pull request by ysndr**
fixes https://github.com/flox/flox/issues/380

### CODE REVIEW

**Comment by ysndr** [comment]
@samrose found the issue, making him unable to run unit tests, to create an issue

**Comment by ysndr** [comment]
based on #369

**Review by mkenigs — APPROVED** [review]
My understanding of this is, if this is correct can you add it to the commit?
floxmeta initialization creates a git commit, so it has to detect name and email for the commit. Detecting name and email is failing currently in some situations. Instead of fixing detection, just drop user floxmeta, since we won't be using it anymore.

**Comment by ysndr** [comment]
@mkenigs exactly, we do fix the detection with the new git config in `Floxmeta2`

**Pull request merged**
