### PR TITLE
refactor: grammar - use contents instead of content

### PR DESCRIPTION
**Pull request by mkenigs**
We use both content and contents throughout the codebase to refer to
what's contained in the manifest. Use contents throughout as it's
consistent with file contents, which sounds more natural to most people.

Change:
manifest_content -> manifest_contents
MANIFEST_CONTENTS -> MANIFEST_CONTENT

### CODE REVIEW

**Comment by mkenigs** [comment]
🤔 it does look like `std::fs` uses `contents`

**Comment by brendaneamon** [comment]
> 🤔 it does look like `std::fs` uses `contents`

@mkenigs, this is perhaps a bit counterintuitive, but I would go with "contents" throughout. I refer to the original meaning of the noun "manifest," which is a list of passengers and good aboard a ship. In that case, we _are_ dealing with things that can be counted.

**Comment by mkenigs** [comment]
> @mkenigs, this is perhaps a bit counterintuitive, but I would go with "contents" throughout.

Well I had a 50-50 shot 🤦 

Just curious would you say file contents too?

**Comment by brendaneamon** [comment]
> > @mkenigs, this is perhaps a bit counterintuitive, but I would go with "contents" throughout.
> 
> Well I had a 50-50 shot 🤦
> 
> Just curious would you say file contents too?

@mkenigs, I would say "the contents of a file" as well, yeah. I think consistency is good either way, so I'm glad you're implementing this change!

**Comment by mkenigs** [comment]
Changed to use contents throughout

**Review by dcarley — APPROVED** [review]
We still use `content` in other non-manifest variable names ([here](https://gist.github.com/dcarley/5e7b235b33c906a43567cc6a236a0525)) but this seems reasonable and shouldn't block this change.

**Pull request merged**
