### PR TITLE
fix(init): remove interactive git repo creation

### PR DESCRIPTION
**Pull request by ysndr**
Simplifying `flox init` while leaving an informational message to users if run outside of a git repository.

New message:

```
$ cd $(mktemp -d)
$ flox init
ERROR: You must be inside of a Git repository to initialize a project
    
    To provide the best possible experience, projects must be under version control.
    Please initialize a project in an existing repo or create one using 'git init'.
```

### CODE REVIEW

**Review by notgne2 — APPROVED** [review]
I guess still waiting for tests but otherwise looks fine.

Makes me wonder if maybe we should do something fancy and artificially force ourselves to check before prompting so we can't run into this again easily. Maybe something like:

```rust
impl Dialog {
  fn prompt(self) -> Option<InquireResult<T>>; // returns false instantly if unpromptable
}
```

or

```rust
struct Promptable;
fn can_prompt() -> Option<Promptable>;

impl Dialog {
  fn prompt(self, _: Promptable); // needs a stupid empty struct to be called, only properly acquired by checking
}
```

**Comment by limeytexan** [comment]
I thought we had discussed that it is out of scope for flox to perform a `git init` within a [project] directory?

* when floxifying a non-git directory then we can drop files in place and build with flox but then all (git-related) publish features are disabled
* when floxifying a git project then it's fair to require that it must be invoked from a git clone

Bottom line, no need to git init AFAIC.

@stahnma - trying to remember if I discussed this with you specifically?

**Comment by stahnma** [comment]
Yeah, that seems right @limeytexan.

**Review by aakropotkin — CHANGES_REQUESTED** [review]
If you could add a test case this will be ready. This message looks good though.

**Comment by ysndr** [comment]
Discussed with @limeytexan  and @tomberek to forego the handholding and make the absence of a git repo a failure case rather than creating a git repo for them.

With the tests now running I'll add a test case for that too in some shape.

**Review by tomberek — APPROVED** [review]

**Comment by aakropotkin** [comment]
Basically add a new `bats` test file based on `multi-env.bats` or `semver-search.bats` which does the following:
```
# flox-bash/tests/non-interactive-init.bats
load test_support.bash;
setup_file() {
  common_setup;
  _flox_init_tmpdir="$( mktemp -d; )";
}
teardown_file() {
  rm -rf "$_flox_init_tmpdir";
}
@test "flox init works non-interactively without -t" {
  run bash -c "cd '$_flox_init_tmpdir'; $FLOX_CLI init --init-git 2>&1;";
  assert_failure;
  # Match some substring from the real error message.
  assert_output --partial "you must select a template";
}
```

**Comment by ysndr** [comment]
Removed the dialog branch, flox now prints an error with some sort of explanation:

```
$ cd $(mktemp -d)
$ flox init
ERROR: You must be inside of a Git repository to initialize a project
    
    To provide the best possible experience, projects must be under version control.
    Please initialize a project in an existing repo or create one using 'git init'.
```

@aakropotkin I'll wait to add a test until #93 is in because that PR restructures a lot of files already.

**Comment by ysndr** [comment]
ping @stahnma, @limeytexan, @robinbrantley for awareness that the behaviour of `flox init` will change with this PR

**Review by aakropotkin — APPROVED** [review]

**Pull request merged**
