### PR TITLE
style: changes the copy for `flox activate` when no .flox file can't be found to use `flox init` in the project

### PR DESCRIPTION
**Pull request by rchatrath7**
Resolves flox/flox#1104

## Proposed Changes
Simply updates copy string in the ErrorMessage

## Release Notes
N/A

### CODE REVIEW

**Comment by ghudgins** [comment]
Thanks for the contribution! Unfortunately even though this is a super small change we'd need you to accept our CLA and add yourself to CONTRIBUTORS.csv, would you mind doing that? See https://github.com/flox/flox/blob/main/CONTRIBUTING.md#cla

**Review by ghudgins — APPROVED** [review]
functionality LGTM

**Comment by rchatrath7** [comment]
Awesome, accepted the CLA!

**Review by mkenigs — CHANGES_REQUESTED** [review]
Thanks for the contribution! 

This changes the error in places where it doesn't quite make sense:
```
$ flox delete
❌ ERROR: Did not find an environment in the current directory.
Run 'flox init' to create an environment.
```

So I think we need to catch this error and then print a custom message for activate. You can look at what we do for install for inspiration https://github.com/flox/flox/blob/aaaac2e75eb84a3e3838d31b8db4d01ab834e852/cli/flox/src/commands/environment.rs#L1144

**Comment by rchatrath7** [comment]
oh sure, that makes sense. I will look to make this update soon!

**Comment by ghudgins** [comment]
pinging!

**Comment by rchatrath7** [comment]
Sorry for the delay! took a stab at error handling and only updating the copy for the activate command. let me know if this is works!

**Review by mkenigs — APPROVED** [review]
Looks great! Thanks so much!

**Pull request merged**
