### PR TITLE
feat: add FLOX_SHELL environment variable

### PR DESCRIPTION
**Pull request by mkenigs**
* Added FLOX_SHELL so the end-user can control which shell `flox
  activate` launches. This allows end-users who don't use `zsh` or
  `bash` to call `flox activate` without having to first launch
  a supported shell.

### CODE REVIEW

**Review by billlevine — CHANGES_REQUESTED** [review]
Add this to the docs for `activate`?

**Comment by mkenigs** [comment]
> Add this to the docs for `activate`?

Good call, fixed

**Review by billlevine — APPROVED** [review]
Nice!

**Comment by mkenigs** [comment]
Had to fix merge conflicts

**Review by zmitchell — APPROVED** [review]

**Review by billlevine — APPROVED** [review]

**Pull request merged**
