### PR TITLE
fix: wrap the filter directly in the reload layer

### PR DESCRIPTION
**Pull request by ysndr**
Wrapping the `Filtered` layer in a `reload::Layer` caused the filter
to be applied globally.
The reload was exposing the filtering of the wrapped layer and applied it globally.
I am personally _not_ convinced this is _expected_ behaviour.
Making only the filter reloadable seems to both simplify the reload handle type
and fix the unwanted propagation of the filter to the global context.
Ordering of the log layer is still significant for unknown reasons:

Filtered layer must come first.
This appears to be the only way to avoid logs of the `flox_command` trace
which is processed by the `log_layer` irrepective of the filter applied to it.
My current understanding is, that it because the `metrics_layer` (at least) is
registering `Interest` for the event and that somehow bypasses the filter?!

### CODE REVIEW

**Comment by ysndr** [comment]
I double checked that events are now being passed through to the metrics module which should fix #1202.

While I'm working on this I can look into https://github.com/flox/product/issues/632 as well, albeit that it is technically unrelated.

**Review by mkenigs — CHANGES_REQUESTED** [review]
blocking: can you add tests or explain why this doesn't need tests?

**Comment by ysndr** [comment]
I'd love to test these things.
However, right now all of this is hanging off a process wide initialized data which we cant test for in unit tests, also the metrics receival is not quite designed with testing.
I can improve on this while working on https://github.com/flox/product/issues/632 though.
The current review is covering https://github.com/flox/flox/issues/1202 only.

**Review by mkenigs — APPROVED** [review]
Okay we can test as part of other tickets

**Review by mkenigs — APPROVED** [review]

**Pull request merged**
