### PR TITLE
chore(show): Rename search-term to pkg-path

### PR DESCRIPTION
**Pull request by dcarley**
## Proposed Changes

To indicate to the user that we're matching a single item rather than searching for multiple packages with a partial string.

I've left the naming in `construct_show_params` and below because it's specific to `pkgdb` terminology.

---

Noticed this while working on https://github.com/flox/flox/pull/1444 which it may cause merge conflicts with but thought it was worth reviewing in its own right.

## Release Notes

N/A, probably not worth mentioning.

### CODE REVIEW

**Review by mkenigs — CHANGES_REQUESTED** [review]
Looks good, but man page needs update

**Comment by mkenigs** [comment]
The man page is generated from `cli/flox/doc/flox-show.md`

**Comment by ysndr** [comment]
@dcarley can you also update the example then?

**Comment by dcarley** [comment]
> @dcarley can you also update the example then?

Just done in https://github.com/flox/flox/pull/1451. They shouldn't merge conflict with each other.

**Review by mkenigs — APPROVED** [review]

**Review by ysndr — APPROVED** [review]

**Review by mkenigs — APPROVED** [review]

**Pull request merged**
