### PR TITLE
feat: scrape under nodePackages (via rules update)

### PR DESCRIPTION
**Pull request by billlevine**
## Proposed Changes

- add a rule to recurse into `legacyPackages.*.nodePackages`

## Release Notes

Additional Node Packages are available.

### CODE REVIEW

**Comment by billlevine** [comment]
Dependent on #1111

**Review by ysndr — APPROVED** [review]
Does scraping `nodePackages` add significant runtime to the scrape?

_probably not, given that nodePackages has "only" 427 packages:_
```
nix eval nixpkgs#nodePackages --apply 'x: builtins.length (builtins.attrNames x)'
427
```

**Comment by ghudgins** [comment]
tried on a branch and wasn't able to return search results for pnpm. not fully integrated yet? something with running this on a branch I don't know

**Comment by ysndr** [comment]
I had to force rebuild pkgdb and remove the old database from the previous scrapes.
seems like either the changes to rules.json.hh are not getting picked up _or_ you have a correct build of pkgdb and just need to delete the old scrape:

```
$ rm ~/.cache/flox/pkgdb-v2/*
$ cd pkgdb
$ make -j 12 -B # -B forces recompilation even if make thinks nothing changed,

$ flox search pnpm
nodePackages.pnpm        Fast, disk space efficient package manager
pnpm-lock-export         A utility for converting pnpm-lock.yaml to other lockfile formats
emacsPackages.pnpm-mode  <no description provided>

Use 'flox show <package>' to see available versions

$ flox search npm
emacsPackages.npm                          <no description provided>
nodePackages.npm                           a package manager for JavaScript
npm-check                                  Check for outdated, incorrect, and unused dependencies
npm-check-updates                          Find newer versions of package dependencies than what your package.json allows
pnpm-lock-export                           A utility for converting pnpm-lock.yaml to other lockfile formats
prefetch-npm-deps                          Prefetch dependencies from npm (for use with `fetchNpmDeps`)
zsh-better-npm-completion                  Better completion for npm
perl536Packages.MooseXStorageFormatJSONpm  A format role for MooseX::Storage using JSON.pm
perl538Packages.MooseXStorageFormatJSONpm  A format role for MooseX::Storage using JSON.pm
perlPackages.MooseXStorageFormatJSONpm     A format role for MooseX::Storage using JSON.pm

Showing 10 of 18 results. Use `flox search npm --all` to see the full list.

Use 'flox show <package>' to see available versions

Related search results for 'nodejs':
nodejs               Event-driven I/O framework for the V8 JavaScript engine
elmPackages.nodejs   Event-driven I/O framework for the V8 JavaScript engine
nodePackages.nodejs  Event-driven I/O framework for the V8 JavaScript engine
```

**Comment by billlevine** [comment]
> tried on a branch and wasn't able to return search results for pnpm. not fully integrated yet? something with running this on a branch I don't know?

Should work after deleting the existing database so it's re-scraped.  I have a follow up PR to automatically invalidate the Db on any rules change.

**Comment by billlevine** [comment]
> Does scraping `nodePackages` add significant runtime to the scrape?
> 
> _probably not, given that nodePackages has "only" 427 packages:_
> 
> ```
> nix eval nixpkgs#nodePackages --apply 'x: builtins.length (builtins.attrNames x)'
> 427
> ```

There is a small impact, due to rules processing/checking and some additional packages, but I didn't not recognize it as significant.  Perhaps 10% slowdown overall.  I did some profiling and there's no glaring inefficiencies that would be quick to address as far as I can tell.

**Pull request merged**
