### PR TITLE
feat: hint `flox show` for more info as part of `flox search`

### PR DESCRIPTION
**Pull request by ysndr**
when displaying flox search {package} results show a line at the bottom about using flox show --> Use `flox show {package}' to see available versions

### CODE REVIEW

**Review by zmitchell — CHANGES_REQUESTED** [review]
For the search tests I'd like you to assert that the "flox show" line is in the output to distinguish between getting two search results back vs. seeing the message and a single search result. Other than that LGTM

**Comment by ysndr** [comment]
Not quite sure what you mean by that, you mean sometheing like this:

```
  assert_equal "$n_lines" 2; # search line + show hint
  assert_equal "$lines[1]" "$SHOW_HINT" 
```

**Comment by zmitchell** [comment]
You can check that the output contains a specific string using this: https://github.com/ztombol/bats-assert#partial-matching

**Comment by zmitchell** [comment]
But your example would also work

**Review by zmitchell — APPROVED** [review]

**Pull request merged**
