### PR TITLE
build: Update catalog API schema and client to 98a0868b

### PR DESCRIPTION
**Pull request by floxbot**
> Adds endpoints and models for sharing catalog info so should not have any impact on the CLI.

### CODE REVIEW

**Review by billlevine — APPROVED** [review]
Adds endpoints and models for sharing catalog info so should not have any impact on the CLI.

**Comment by ysndr** [comment]
does this require updating the mocks?

**Comment by billlevine** [comment]
> does this require updating the mocks?

I tried `just gen-data`, nothing was updated, so I think we're all clear.

**Comment by ysndr** [comment]
unless you add a new mock, you need to run `just gen-data -f` to regen existing ones, but even with that only `rev`s, store paths and such change. i think we should still do these occasionally, but its not necessary for this PR per se.

**Pull request merged**
