### PR TITLE
feat(containerize): add `--tag` option

### PR DESCRIPTION
**Pull request by bryanhonof**
## Proposed Changes

Closes: flox/product#771

## Release Notes

- `flox containerize --tag ...` now sets the resulting container's tag to the value of the `tag` flag.
- `flox containerize` now sets the resulting container's tag to `latest` by default if `--tag` isn't set.

### CODE REVIEW

**Comment by bryanhonof** [comment]
I still have to add the `--tag` flag to the Rust part of things.
Just have to figure out how. 😅

**Comment by ysndr** [comment]
--flag or --tag 🤔

**Review by ysndr — APPROVED** [review]
Question (non-blocking): should it be possible to add multiple tags?

**Comment by ysndr** [comment]
@bryanhonof can you sqush rename the commits a bit, at the very least they are still saying `--flag` :)

**Comment by ysndr** [comment]
doesnt seem there are any changes to the tests due to my rebase.

should there be a command to read the customization before trying to read the tag?

https://github.com/flox/flox/pull/2142/files#diff-c73e35d1f06632f0ef60cd61de1390e7209482a5a64b7acb930fe1e28b5f4d0fR230-R233

**Comment by bryanhonof** [comment]
> doesnt seem there are any changes to the tests due to my rebase.
>
> should there be a command to read the customization before trying to read the tag?

@ysndr No, I hadn't finished that test yet, apparently. I was taking a wrong approach at first, should be fine now.


> Question (non-blocking): should it be possible to add multiple tags?

I honestly don't know.
Wouldn't be surprised if this worked, but I've never seen it out in the wild all that much, t.b.h.
So, I think it's fine for now until the need arrives.

**Pull request merged**
