### PR TITLE
fix: drop --bash-passthru

### PR DESCRIPTION
**Pull request by mkenigs**
- Drop Bash code
- Drop Rust code implementing --bash-passthru
- Make develop an alias of activate
- Mark generations, history, push, pull, rollback, switch-generation, upgrade, auth with
  todo!("this command is planned for a future release")
  Running one of these commands will result in the output:
  ```
  thread 'main' panicked at 'not yet implemented: this command is planned for a future release', crates/flox/src/commands/environment.rs:621:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```
- Mark export, import, print-dev-env, git, gh with
  todo!("deprecated")
  These commands will be dropped in a followup PR

### CODE REVIEW

**Comment by mkenigs** [comment]
@ghudgins @stahnma can you confirm whether we're okay with the behavior described for generations, history, push, pull, rollback, upgrade, and auth until they are implemented in Rust?

**Comment by mkenigs** [comment]
I can also easily get rid of the panic if that's too scary

**Comment by stahnma** [comment]
It's fine until they are reimplemented. (Note they don't have to be rust). 

Also wait until release Thursday to merge this

**Review by stahnma — APPROVED** [review]
I'm probably not the person to review the change in detail. But the comments and methods involved seem correct

**Review by ghudgins — APPROVED** [review]

**Comment by mkenigs** [comment]
This is ready for review, but leaving as draft so it doesn't get merged

**Comment by mkenigs** [comment]
Created https://github.com/flox/flox/issues/336 for followup

**Pull request merged**
