### PR TITLE
docs: added a dot and removed an extra space in README

### PR DESCRIPTION
**Pull request by Cadienvan**
## Proposed Changes

A simple correction in the README, hope to be of help!

## Release Notes

N/A

### CODE REVIEW

**Comment by mkenigs** [comment]
Thanks for the contribution! Unfortunately even though this is a super small change we'd need you to accept our CLA and add yourself to CONTRIBUTORS.csv, would you mind doing that? See https://github.com/flox/flox/blob/main/CONTRIBUTING.md#cla

**Comment by Cadienvan** [comment]
@mkenigs there you go :)

**Comment by mkenigs** [comment]
Thanks!

**Comment by limeytexan** [comment]
@Cadienvan - just want to say thanks again for being a contributor, and we look forward to working with you!

**Comment by Cadienvan** [comment]
It's been a pleasure!

**Pull request merged**
