### PR TITLE
docs: fix typo in README.md

### PR DESCRIPTION
**Pull request by PyGeek03**

### CODE REVIEW

**Review by ysndr — APPROVED** [review]

**Review by ysndr — CHANGES_REQUESTED** [review]
Thanks for the contribution!
Unfortunately even though this is a super small change we'd need you to accept our CLA and add yourself to CONTRIBUTORS.csv, would you mind doing that? See https://github.com/flox/flox/blob/main/CONTRIBUTING.md#cla

**Comment by ghudgins** [comment]
just checking in on this @PyGeek03 - are you going to be able to sign the CLA?

**Comment by PyGeek03** [comment]
Hi, is it possible for me to add myself to CONTRIBUTORS.csv without adding an email address? I already receive enough spam in my inbox 😅

**Comment by ghudgins** [comment]
@PyGeek03 this is fine. can you update the column to say `GitHub handle or Email` and then just include your GitHub handle?

**Review by ghudgins — APPROVED** [review]

**Review by mkenigs — APPROVED** [review]

**Pull request merged**
