### PR TITLE
test: add prop_assume to rule out edge case

### PR DESCRIPTION
**Pull request by mkenigs**
`read_environment_registry` does not need to handle a directory existing, so add a `prop_assume` preventing this test case.

### CODE REVIEW

**Review by zmitchell — COMMENTED** [review]
Review from my phone, but you still need to handle the `/` and `.` cases

**Comment by mkenigs** [comment]
> Review from my phone, but you still need to handle the `/` and `.` cases

Aren't both of those excluded by `path.is_file()`?

**Comment by zmitchell** [comment]
Ah, yeah. That’s what I get for doing code review from the passenger seat.

**Review by zmitchell — APPROVED** [review]

**Comment by dcarley** [comment]
Thanks! This was related to the test failure I saw here: https://github.com/flox/flox/actions/runs/8725674651/job/23939202159#step:6:378

**Pull request merged**
